// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY ?? '';

// Use localStorage only in the browser (avoids "localStorage is not defined" during Next.js build / Vercel deploy)
const isBrowser = typeof window !== "undefined";
const storage = isBrowser
  ? localStorage
  : (({
      getItem: () => null,
      setItem: () => {},
      removeItem: () => {},
    } as unknown) as Storage);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage,
    persistSession: true,
    autoRefreshToken: true,
  },
});